<%@ page pageEncoding="UTF-8" %>  
<script src="resources/js/extendjs.js?jsVersion=<%=jsVersion%>"></script>
<style>
    .edui-default .edui-dialog {
        z-index:19999;
    }
</style>
<script>
    window.UEDITOR_HOME_URL =  root+"/frame/component/ueditor/";
</script>
<script src="resources/js/ueditor_config.js?jsVersion=<%=jsVersion%>"></script>
<script src="frame/component/ueditor/ueditor_all.js?jsVersion=<%=jsVersion%>"></script>
<script src="frame/component/ueditor/uparse.js?jsVersion=<%=jsVersion%>"></script>


